In [91]:
# 1. Import the numpy package under the name np
import numpy as np

In [93]:
# 2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/kshno/anaconda3/Library/include
    lib directory: C:/Users/kshno/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

In [95]:
# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
a = np.random.randn(2, 3, 5)

In [97]:
# 4. Print a
print(a)

[[[ 0.51289093  0.60941971 -0.16639195  0.94994103 -1.24352384]
  [ 0.12318304 -2.00373867 -1.04412502  1.11192634  0.58787829]
  [-1.10396258  2.13382021  2.21697427  0.46803774 -0.31686625]]

 [[ 0.51807043 -0.78434278  0.13669463  2.28561586  0.34572975]
  [ 0.31307379  0.47004352 -0.50025639 -0.37198549 -0.71063589]
  [-2.23738351 -1.73239138  0.10125341 -0.19847513 -1.02420246]]]


In [99]:
# 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [101]:
# 6. Print b
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [103]:
# 7. Do a and b have the same size? How do you prove that in Python code?
print(a.size == b.size)

True


In [105]:
# 8. Are you able to add a and b? Why or why not?
try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


In [107]:
# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)


In [109]:
# 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?
d = a + c
print(d)

[[[ 1.51289093  1.60941971  0.83360805  1.94994103 -0.24352384]
  [ 1.12318304 -1.00373867 -0.04412502  2.11192634  1.58787829]
  [-0.10396258  3.13382021  3.21697427  1.46803774  0.68313375]]

 [[ 1.51807043  0.21565722  1.13669463  3.28561586  1.34572975]
  [ 1.31307379  1.47004352  0.49974361  0.62801451  0.28936411]
  [-1.23738351 -0.73239138  1.10125341  0.80152487 -0.02420246]]]


In [111]:
# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("a:\n", a)
print("d:\n", d)

a:
 [[[ 0.51289093  0.60941971 -0.16639195  0.94994103 -1.24352384]
  [ 0.12318304 -2.00373867 -1.04412502  1.11192634  0.58787829]
  [-1.10396258  2.13382021  2.21697427  0.46803774 -0.31686625]]

 [[ 0.51807043 -0.78434278  0.13669463  2.28561586  0.34572975]
  [ 0.31307379  0.47004352 -0.50025639 -0.37198549 -0.71063589]
  [-2.23738351 -1.73239138  0.10125341 -0.19847513 -1.02420246]]]
d:
 [[[ 1.51289093  1.60941971  0.83360805  1.94994103 -0.24352384]
  [ 1.12318304 -1.00373867 -0.04412502  2.11192634  1.58787829]
  [-0.10396258  3.13382021  3.21697427  1.46803774  0.68313375]]

 [[ 1.51807043  0.21565722  1.13669463  3.28561586  1.34572975]
  [ 1.31307379  1.47004352  0.49974361  0.62801451  0.28936411]
  [-1.23738351 -0.73239138  1.10125341  0.80152487 -0.02420246]]]


In [113]:
# 12. Multiply a and c. Assign the result to e.
e = a * c
print(e)

[[[ 0.51289093  0.60941971 -0.16639195  0.94994103 -1.24352384]
  [ 0.12318304 -2.00373867 -1.04412502  1.11192634  0.58787829]
  [-1.10396258  2.13382021  2.21697427  0.46803774 -0.31686625]]

 [[ 0.51807043 -0.78434278  0.13669463  2.28561586  0.34572975]
  [ 0.31307379  0.47004352 -0.50025639 -0.37198549 -0.71063589]
  [-2.23738351 -1.73239138  0.10125341 -0.19847513 -1.02420246]]]


In [115]:
# 13. Does e equal to a? Why or why not?
print(np.array_equal(e, a))

True


In [117]:
# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean".
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("d_max:", d_max)
print("d_min:", d_min)
print("d_mean:", d_mean)

d_max: 3.2856158635267563
d_min: -1.237383511824362
d_mean: 0.9815423880112941


In [119]:
# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty(d.shape)
print(f)

[[[0.51289093 0.60941971 0.16639195 0.94994103 1.24352384]
  [0.12318304 2.00373867 1.04412502 1.11192634 0.58787829]
  [1.10396258 2.13382021 2.21697427 0.46803774 0.31686625]]

 [[0.51807043 0.78434278 0.13669463 2.28561586 0.34572975]
  [0.31307379 0.47004352 0.50025639 0.37198549 0.71063589]
  [2.23738351 1.73239138 0.10125341 0.19847513 1.02420246]]]


In [121]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
f = np.empty(d.shape)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print(f)

[[[ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  75. 100.  75.]
  [ 75.  75.  25.  25.  25.]
  [  0.  25.  75.  25.  25.]]]


In [123]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


print("d:\n", d)
print("f:\n", f)

d:
 [[[ 1.51289093  1.60941971  0.83360805  1.94994103 -0.24352384]
  [ 1.12318304 -1.00373867 -0.04412502  2.11192634  1.58787829]
  [-0.10396258  3.13382021  3.21697427  1.46803774  0.68313375]]

 [[ 1.51807043  0.21565722  1.13669463  3.28561586  1.34572975]
  [ 1.31307379  1.47004352  0.49974361  0.62801451  0.28936411]
  [-1.23738351 -0.73239138  1.10125341  0.80152487 -0.02420246]]]
f:
 [[[ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  75. 100.  75.]
  [ 75.  75.  25.  25.  25.]
  [  0.  25.  75.  25.  25.]]]


In [125]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
a = np.random.randn(2, 3, 5)

print("a:\n", a)

b = np.ones((5, 2, 3))

print("b:\n", b)

c = np.transpose(b, (1, 2, 0))

d = a + c

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

f = np.empty(d.shape, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 'A'
            elif d[i, j, k] == d_max:
                f[i, j, k] = 'E'
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 'C'
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 'B'
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 'D'

print("d:\n", d)
print("f:\n", f)

a:
 [[[-1.80555711  0.42449699  0.97966455  1.18489526 -1.01983449]
  [-0.03105534 -0.81909656  0.79527872 -0.57937706 -1.96723084]
  [ 0.09807858  0.26478916  1.19756014 -0.14797622 -0.51225286]]

 [[ 0.19184078 -0.14493872  0.62990013  0.27028547 -0.84753394]
  [-0.62749025  2.28289587  0.87647448 -0.90186253 -1.82012102]
  [-0.30868094  1.08999952 -0.44367401  0.42616382 -1.28228409]]]
b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
d:
 [[[-0.80555711  1.42449699  1.97966455  2.18489526 -0.01983449]
  [ 0.96894466  0.18090344  1.79527872  0.42062294 -0.96723084]
  [ 1.09807858  1.26478916  2.19756014  0.85202378  0.48774714]]

 [[ 1.19184078  0.85506128  1.62990013  1.27028547  0.15246606]
  [ 0.37250975  3.28289587  1.87647448  0.09813747 -0.82012102]
  [ 0.69131906  2.08999952  0.55632599  1.42616382 -0.28228409]]]
f:
 [[['B' 'D' 'D' 'D' 'B']
  ['D' 'B' 'D' 'B' 'A']
  ['D' 'D' 'D' 'B' '